version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate ./base/base.json
      - run:
          name: Validate snowflake
          command: packer validate ./snowflake/snowflake.json
  build-snowflake:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build snowflake
          command: packer build ./snowflake/snowflake.json
      - store_artifacts:
          path: manifest-snowflake.json
  canary-snowflake:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Install redis
          command: apt-get install redis-server -y 
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-snowflake:
          requires:
            - validate
      - canary-snowflake:
          requires:
            - build-snowflake
